### ISSUE TITLE
Invalid argument not valid semver

### ISSUE THREAD

**Issue by nickvgn** [aleqsio/new-arch-helper#1]
Hello there! Thank you for making this. I'm seeing an exception thrown when I try to run it however. Could I possibly be doing something wrong?

![Screenshot 2024-04-10 at 8 12 54 AM](https://github.com/aleqsio/new-arch-helper/assets/42023889/6b461633-26c0-4bfb-aa35-eb4a4192a371)

**Comment by ospfranco** [comment]
@nickvgn you are not doing something wrong. The library is not handling an edge case correctly. You probably have a locally linked dependency.

![CleanShot 2024-04-10 at 09 57 07@2x](https://github.com/aleqsio/new-arch-helper/assets/1634213/de60b45f-960c-440f-8cb1-7265b1a8cf0d)

@aleqsio Also facing this. In case there is a locally linked package you probably want to catch the error when trying to compare versions and just output it is not possible to determine what is wrong

**Comment by aleqsio** [comment]
Thanks, I'll try to push a quick update!

**Comment by aleqsio** [comment]
Fixed in @1.1.3, remember to run `npx new-arch@latest`
