### ISSUE TITLE
Getting an error when trying to run

### ISSUE THREAD

**Issue by oferRounds** [aleqsio/new-arch-helper#4]
Any idea?

<img width="959" alt="image" src="https://github.com/aleqsio/new-arch-helper/assets/1477963/c02b36ca-484d-47c1-8ea5-4016275edee4">

**Comment by kapir** [comment]
The command is npx new-arc**h**

You are missing the letter h at the end

**Comment by oferRounds** [comment]
oh right, sorry! Thank you!
