### ISSUE TITLE
Completely broken?

### ISSUE THREAD

**Issue by wojtekmaj** [aleqsio/new-arch-helper#6]
There's likely been a change to the sheet it's based on or something similar, because I'm getting 100% failure rate:

<img width="760" alt="image" src="https://github.com/user-attachments/assets/3c0094b8-84a7-4288-a696-1aff3f0a6d94">

**Comment by aleqsio** [comment]
Oh, perhaps it's time to deprecate this tool since it landed in expo-doctor (and it uses react-native.directory)!

I recommend using this instead:
https://docs.expo.dev/guides/new-architecture/#validate-your-dependencies-with-react-native-directory
